## Import Libraries

In [4]:
import numpy as np

## Basic Arrays

In [5]:
one_d = np.array([1,2,3,4,5,6], dtype='float')
one_d

array([1., 2., 3., 4., 5., 6.])

In [6]:
two_d = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], dtype='float')
two_d

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

In [7]:
three_d = np.array([[[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]] , [[1,2,3],[4,5,6],[7,8,9]]], dtype='float')
three_d

array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]])

## Array Features

In [8]:
print(two_d.ndim)
print(two_d.size)
print(two_d.shape)
print(two_d)

2
12
(4, 3)
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [9]:
print(three_d.shape)
print(three_d)

(4, 3, 3)
[[[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]

 [[1. 2. 3.]
  [4. 5. 6.]
  [7. 8. 9.]]]


## Some specific Arrays

In [10]:
zero_array = np.zeros((3,3))
print(f'zero_array:\n {zero_array}\n')

one_array = np.ones((3,5))
print(f'one_array:\n {one_array}\n')

full_array = np.full((5,3), 15)
print(f'full_array:\n {full_array}\n')

random_array = np.random.randint(0,10,(3,4))
print(f'random_array:\n {random_array}\n')

zero_array:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

one_array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

full_array:
 [[15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]
 [15 15 15]]

random_array:
 [[8 4 9 2]
 [1 6 6 6]
 [6 5 7 6]]



## Sequential Arrays

In [11]:
arr = np.arange(0,20)
print(f'arrange: \n{arr}\n')

arr3ta3ta = np.arange(0,20,3)
print(f'arr3ta3ta: \n{arr3ta3ta}\n')

arr2 = np.linspace(0,50,10)
print(f'linspace: \n{arr2}\n')

arrange: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

arr3ta3ta: 
[ 0  3  6  9 12 15 18]

linspace: 
[ 0.          5.55555556 11.11111111 16.66666667 22.22222222 27.77777778
 33.33333333 38.88888889 44.44444444 50.        ]

