## Import Libraries

In [3]:
import numpy as np

## Indexing

In [4]:
a = np.arange(0,12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [6]:
a[3]

np.int64(3)

In [7]:
a[3]=15
print(a)

[ 0  1  2 15  4  5  6  7  8  9 10 11]


In [8]:
a[3]

np.int64(15)

In [10]:
b = np.random.randint(0,12,(3,4))
print(b)

[[ 0 11  8  0]
 [ 5  3  8  9]
 [ 5 11 11  3]]


In [12]:
print(b[1,2])

8


In [13]:
b[1,2] = 9
b[1,2]

np.int32(9)

## Slicing

In [ ]:
b[0:2 ,:]

array([[ 0, 11,  8,  0],
       [ 5,  3,  9,  9]], dtype=int32)

In [15]:
b[0:2 , 1:3]

array([[11,  8],
       [ 3,  9]], dtype=int32)

In [16]:
b[0:2]

array([[ 0, 11,  8,  0],
       [ 5,  3,  9,  9]], dtype=int32)

In [17]:
b[:,0:2]

array([[ 0, 11],
       [ 5,  3],
       [ 5, 11]], dtype=int32)

In [68]:
b

array([[ 0,  5,  8,  0],
       [ 5,  5,  9,  9],
       [ 5,  5, 11,  3]], dtype=int32)

In [70]:
b_copy = b.copy()
print(b_copy)
b[: , 1] = 5
print(b[: , 1])



[[ 0  5  8  0]
 [ 5  5  9  9]
 [ 5  5 11  3]]
[5 5 5]


In [56]:
c = np.random.randint(1,30,(3,4,2))
c

array([[[26, 10],
        [ 2, 28],
        [18, 13],
        [14, 26]],

       [[21, 26],
        [13, 19],
        [ 7, 12],
        [18, 18]],

       [[ 2,  2],
        [ 2,  3],
        [ 7,  7],
        [20,  7]]], dtype=int32)

In [19]:
c.shape

(3, 4, 2)

In [20]:
c[1 , :, :]

array([[11, 25],
       [19,  8],
       [10, 12],
       [23, 17]], dtype=int32)

In [23]:
c[0:2 , :, :]

array([[[18, 15],
        [23,  6],
        [17, 28],
        [25, 16]],

       [[11, 25],
        [19,  8],
        [10, 12],
        [23, 17]]], dtype=int32)

In [29]:
c[1 , -1, :]

array([23, 17], dtype=int32)

In [38]:
c[1 , -3 :-1, :]

array([[19,  8],
       [10, 12]], dtype=int32)

## Reshape

In [44]:
g = np.arange(0,12)
print(g)

g = g.reshape(3,4)
print(g)
print(g.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12


In [46]:
g = g.reshape(-1,4)
print(g)                              #khodesh mohasebe mikoneh ke chetori 4 satri besheh

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
g = g.reshape(4,-1)
print(g)                             #khodesh mohasebe mikoneh ke chetori 4 radifi besheh

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## Transpose

In [79]:
my_arr = np.arange(1,13).reshape(3,4)
print(f'original array:\n {my_arr}\n shape: {my_arr.shape}')

my_arr_T = my_arr.T
print(f'Transposed array:\n {my_arr_T}\n shape: {my_arr_T.shape}')

original array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
 shape: (3, 4)
Transposed array:
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
 shape: (4, 3)


In [91]:
my_arr2 = np.arange(1,25).reshape(-1,3,4)
print(f'original array:\n {my_arr2}\n shape: {my_arr2.shape}')
my_arr2_T = my_arr2.transpose(2,1,0)
print(f'Transposed array:\n {my_arr2_T}\n shape: {my_arr2_T.shape}')

original array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
 shape: (2, 3, 4)
Transposed array:
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
 shape: (4, 3, 2)


In [93]:
new_arr = my_arr2.swapaxes(0,2)
print(f'original array:\n {new_arr}\n shape: {new_arr.shape}')

original array:
 [[[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]

 [[ 4 16]
  [ 8 20]
  [12 24]]]
 shape: (4, 3, 2)


## Concatenation

In [ ]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(13,31).reshape(3,6)
                                               #amood = 0    ofogh = 1
c = np.concatenate([a,b], axis=1)

In [112]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
b

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [114]:
c

array([[ 1,  2,  3,  4, 13, 14, 15, 16, 17, 18],
       [ 5,  6,  7,  8, 19, 20, 21, 22, 23, 24],
       [ 9, 10, 11, 12, 25, 26, 27, 28, 29, 30]])

In [115]:
a = np.arange(1,13).reshape(4,3)
b = np.arange(13,31).reshape(6,3)
                                               #amood = 0    ofogh = 1
c = np.concatenate([a,b], axis=0)

In [117]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [118]:
b

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [119]:
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30]])

In [ ]:
a = np.arange(1,37).reshape(6,3,2)
b = np.arange(1,55).reshape(6,3,3)
                                               #amood = 0    ofogh = 1    omgh = 2
c = np.concatenate([a,b], axis=2)

In [124]:
a

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]],

       [[25, 26],
        [27, 28],
        [29, 30]],

       [[31, 32],
        [33, 34],
        [35, 36]]])

In [125]:
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]],

       [[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[37, 38, 39],
        [40, 41, 42],
        [43, 44, 45]],

       [[46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [127]:
c

array([[[ 1,  2,  1,  2,  3],
        [ 3,  4,  4,  5,  6],
        [ 5,  6,  7,  8,  9]],

       [[ 7,  8, 10, 11, 12],
        [ 9, 10, 13, 14, 15],
        [11, 12, 16, 17, 18]],

       [[13, 14, 19, 20, 21],
        [15, 16, 22, 23, 24],
        [17, 18, 25, 26, 27]],

       [[19, 20, 28, 29, 30],
        [21, 22, 31, 32, 33],
        [23, 24, 34, 35, 36]],

       [[25, 26, 37, 38, 39],
        [27, 28, 40, 41, 42],
        [29, 30, 43, 44, 45]],

       [[31, 32, 46, 47, 48],
        [33, 34, 49, 50, 51],
        [35, 36, 52, 53, 54]]])

## Split

In [132]:
a = np.arange(1,13).reshape(3,4)
b = np.arange(13,25).reshape(3,4)
                                               #amood = 0    ofogh = 1
c = np.concatenate([a,b], axis=1)

In [129]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
b

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [133]:
c

array([[ 1,  2,  3,  4, 13, 14, 15, 16],
       [ 5,  6,  7,  8, 17, 18, 19, 20],
       [ 9, 10, 11, 12, 21, 22, 23, 24]])

In [136]:
arr_list = np.split(c, 2, axis=1)                      #amood = 0    ofogh = 1
arr_list

[array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [137]:
arr_list = np.split(c, [2], axis=1)                      #amood = 0    ofogh = 1
arr_list

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4, 13, 14, 15, 16],
        [ 7,  8, 17, 18, 19, 20],
        [11, 12, 21, 22, 23, 24]])]

In [138]:
arr_list = np.split(c, [2,4], axis=1)                      #amood = 0    ofogh = 1
arr_list

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]]),
 array([[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]])]

In [ ]:
arr_list[0]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [140]:
arr_list[1]

array([[ 3,  4],
       [ 7,  8],
       [11, 12]])

In [141]:
arr_list[2]

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])