## Import Libraries

In [2]:
import numpy as np

## Universal Functions

In [3]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
a * 10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [17]:
# sum
sum = a + 5
print(f'sum\n{sum}\n')

sum2 = np.add(a,5)
print(f'sum2\n{sum2}\n')

# subtract
sub = a - 10
print(f'sub\n{sub}\n')

sub2 = np.subtract(a,10)
print(f'sub2\n{sub2}\n')

sum
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

sum2
[[ 6  7  8  9]
 [10 11 12 13]
 [14 15 16 17]]

sub
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]

sub2
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]



In [18]:
# multiple
mul = a * 10
print(f'mul\n{mul}\n')

mul2 = np.multiply(a,10)
print(f'mul2\n{mul2}\n')

# divide
div = a / 5
print(f'div\n{div}\n')

div2 = np.divide(a,5)
print(f'div2\n{div2}\n')

mul
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

mul2
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]

div
[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]]

div2
[[0.2 0.4 0.6 0.8]
 [1.  1.2 1.4 1.6]
 [1.8 2.  2.2 2.4]]



In [ ]:
# sqrt radical forje 2
sqrt = np.sqrt(a)
print(f'sqrt\n{sqrt}\n')

# log
log = np.log(a)
print(f'log\n{log}\n')

#     a
# log           'a' can't be 0 in log
#     e=2.7


sqrt
[[1.         1.41421356 1.73205081 2.        ]
 [2.23606798 2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479 3.46410162]]

log
[[0.         0.69314718 1.09861229 1.38629436]
 [1.60943791 1.79175947 1.94591015 2.07944154]
 [2.19722458 2.30258509 2.39789527 2.48490665]]



In [29]:
# exponential   توابع نمایی
exp = np.exp(a)
print(f'exp\n{exp}\n')

#    a
#   e                  'e' be tavan 2.7  normal sazi data



print(f'sub\n{sub}\n')          # abstract    قدر مطلق

abs = np.abs(sub)          # مقادیر منفی رو مثبت می کنه
print(f'abs\n{abs}\n')

exp
[[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01]
 [1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03]
 [8.10308393e+03 2.20264658e+04 5.98741417e+04 1.62754791e+05]]

sub
[[-9 -8 -7 -6]
 [-5 -4 -3 -2]
 [-1  0  1  2]]

abs
[[9 8 7 6]
 [5 4 3 2]
 [1 0 1 2]]



In [30]:
'''
Link to the numpy reference for Universal functions:
https://numpy.org/doc/stable/reference/ufuncs.html#methods

'''

'\nLink to the numpy reference for Universal functions:\nhttps://numpy.org/doc/stable/reference/ufuncs.html#methods\n\n'

In [32]:
# (3.4) * (4,2)         4) * (4   اینا باید برابر باشن
b = np.arange(1,9).reshape(4,2)
print(a,'\n')
print(b,'\n')

result = np.matmul(a,b)     # matrix multiplication
print(f'result\n {result} \n')

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

result
 [[ 50  60]
 [114 140]
 [178 220]] 



In [35]:
g = 1 + 6 + 15 + 28
print(g)
h = 5 + 18 + 35 + 56
print(h)
i = 9 + 30 + 55 + 84
print(i)


50
114
178


In [ ]:
# [1,2,3,4] * [1,2,3,4]                    همین ریزالت بالا رو داد. ضرب نقطه  ای
a = np.array([1,2,3,4])
b = np.array([1,3,5,7])
result2 = np.dot(a,b)
print(f'result2\n {result2} \n')

result2
50

