## Import Libraries

In [2]:
import numpy as np

## Aggregation Functions   توابع تجمیعی

In [15]:
students = [
    [14,16,20,18,10],   #Math
    [5,15,17,20,12]    #science
]

students_arr = np.array(students, dtype='int')
print(students_arr)

[[14 16 20 18 10]
 [ 5 15 17 20 12]]


**Sum**

In [16]:
#np.add
math = np.sum(students_arr, axis=1)
print(f'sum of each math: {math[0]}')
print(f'sum of each science: {math[1]}')


sum of each math: 78
sum of each science: 69


In [20]:
student_score = np.sum(students_arr, axis=0)
for index, i in enumerate (student_score):
    print(f'student_{index}:{i}')

student_0:19
student_1:31
student_2:37
student_3:38
student_4:22


In [21]:
sum_all = np.sum(students_arr)
print(sum_all)

147


**Mean**

In [22]:
students_arr

array([[14, 16, 20, 18, 10],
       [ 5, 15, 17, 20, 12]])

In [27]:
lesson_mean = np.mean(students_arr, axis=1)
print(f'Mean of Math: {lesson_mean[0]}')
print(f'Mean of Science: {lesson_mean[1]}')

Mean of Math: 15.6
Mean of Science: 13.8


In [ ]:
student_mean_score = np.mean(students_arr, axis=0)
for index, i in enumerate(student_mean_score):
    print(f'student_{index+1}: {i}')

student_1: 9.5
student_2: 15.5
student_3: 18.5
student_4: 19.0
student_5: 11.0


In [32]:
mean_all = np.mean(students_arr)
print(mean_all)

14.7


**Min, Max**

In [34]:
lesson_minimum = np.min(students_arr, axis=1)
print(f'min of math: {lesson_minimum[0]}')
print(f'min of science: {lesson_minimum[1]}')

min of math: 10
min of science: 5


In [35]:
lesson_maximum = np.max(students_arr,axis=1)
print(f'max of math: {lesson_maximum[0]}')
print(f'max of science: {lesson_maximum[1]}')

max of math: 20
max of science: 20


In [36]:
student_min_score = np.min(students_arr,axis=0)
for index,i in enumerate(student_min_score):
    print(f'student_{index+1}: {i}')

student_1: 5
student_2: 15
student_3: 17
student_4: 18
student_5: 10


In [37]:
student_max_score = np.max(students_arr, axis=0)
for index, i in enumerate(student_max_score):
    print(f'student_{index+1}:{i}')

student_1:14
student_2:16
student_3:20
student_4:20
student_5:12


**argmin , argmsx**

In [60]:
students_arr

array([[14, 16, 20, 18, 10],
       [ 5, 15, 17, 20, 12]])

In [57]:
min_math = np.min(students_arr,axis=1)
index_min_math = np.argmin(students_arr,axis=1)
print(f'student_{index_min_math[0]}: {min_math[0]}')

student_4: 10


In [59]:
students_argmax_score = np.argmax(students_arr, axis=0)
for index, i in enumerate(students_argmax_score):
    print(f'student_{index+1}: {i}')

student_1: 0
student_2: 0
student_3: 0
student_4: 1
student_5: 1


**Median**

In [ ]:
# [1,2,3,4,5] -> 15/5 = 3  : mean
# [1,2,3,4,5] -> 3  :  median

# [1,2,4,5] -> median?
print(np.median([1,2,4,5]))
# [1.0,2.5,4.0,5.0] -> median?
print(np.median([1.0,2.5,4.0,5.0]))

3.0
3.25


In [41]:
lesson_median = np.median(students_arr, axis=1)

print(f'Median of Math: {lesson_median[0]}')
print(f'Median of Science: {lesson_median[1]}')


Median of Math: 16.0
Median of Science: 15.0


In [45]:
students_median_score = np.median(students_arr, axis=0)
for index, i in enumerate(students_median_score):
    print(f'student_{index+1}: {i}')

student_1: 9.5
student_2: 15.5
student_3: 18.5
student_4: 19.0
student_5: 11.0


In [46]:
all_median = np.median(students_arr)
all_median

np.float64(15.5)

**std : standard deviation**      انحراف از معیار

In [50]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [-10,-5,0,5,10]

print(f'std of a :{np.std(a)}')
print(f'std of b : {np.std(b)}')

print(f'mean of a:{np.mean(a)}')
print(f'mean of b:{np.mean(b)}')

std of a :2.8722813232690143
std of b : 7.0710678118654755
mean of a:5.5
mean of b:0.0


In [51]:
students_arr

array([[14, 16, 20, 18, 10],
       [ 5, 15, 17, 20, 12]])

In [52]:
lesson_std = np.std(students_arr, axis=1)

print(f'std of Math: {lesson_std[0]}')
print(f'std of Science: {lesson_std[1]}')


std of Math: 3.4409301068170506
std of Science: 5.114684741017769


In [54]:
students_std_score = np.std(students_arr, axis=0)
for index, i in enumerate(students_std_score):
    print(f'student_{index+1}: {i}')

student_1: 4.5
student_2: 0.5
student_3: 1.5
student_4: 1.0
student_5: 1.0


In [56]:
all_std = np.std(students_arr)
all_std

np.float64(4.450842616853577)

**Percentaile**     دهک

In [61]:
my_arr = np.arange(1,101)
print(my_arr)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]


In [63]:
print(f'the 0th percentaile of the data is at :{np.percentile(my_arr,0)} ')
print(f'the 25th percentaile of the data is at :{np.percentile(my_arr,25)} ')
print(f'the 50th percentaile of the data is at :{np.percentile(my_arr,50)} ')
print(f'the 0th percentaile of the data is at :{np.percentile(my_arr,75)} ')
print(f'the 100th percentaile of the data is at :{np.percentile(my_arr,100)} ')

the 0th percentaile of the data is at :1.0 
the 25th percentaile of the data is at :25.75 
the 50th percentaile of the data is at :50.5 
the 0th percentaile of the data is at :75.25 
the 100th percentaile of the data is at :100.0 
