## Introduction

####  **Project Story:**
A regional education director has decided to use student grade data from 4 schools to examine the overall and individual performance of students. The goals of this analysis are:
- Identify outstanding students and those who need support  
- Assess the quality of education at each school  
- Prepare a report for the educational council meeting

---

####  **Available Data:**
- 4 schools  
- 5 students per school  
- Each student has scores in 3 subjects: Math, Science, and Persian Language  
- Scores are recorded as numbers between 10 and 20

---

####  **Key Analysis Questions:**
1. What is each student's average score?  
2. Which students have a performance above 17?  
3. Which school has the highest average score?  
4. Which subject has the greatest score dispersion (standard deviation)?  
5. Do the scores need to be scaled for better comparison?

## Import Libraries

In [1]:
import numpy as np

## Data Generation

In [41]:
# Schoole -> student -> lesson
#(4, 5, 3)  3d matris
data = np.random.randint(10,21,(4,5,3))
print(f'shape of the Data: {data.shape}')
print(f'size of data : {data.size}')
print(f'Data type : {data.dtype}')

print('raw data:', '\n',data)

shape of the Data: (4, 5, 3)
size of data : 60
Data type : int32
raw data: 
 [[[20 12 17]
  [16 18 20]
  [13 10 17]
  [16 16 17]
  [20 14 14]]

 [[17 15 17]
  [14 11 15]
  [17 11 19]
  [17 14 16]
  [14 10 16]]

 [[12 11 12]
  [13 14 19]
  [19 19 19]
  [18 19 12]
  [10 15 14]]

 [[20 14 10]
  [12 14 20]
  [13 18 16]
  [19 15 18]
  [17 12 12]]]


## Data preprocessing

In [42]:
#(4,5,3)
full_students = data.reshape(-1,3)  #منفی یک خودش میفهمه چند تا ردیف باید بده و 3 تا ستون
print(f'shape of the Data: {full_students.shape}')
print(f'size of data : {full_students.size}')
print(f'Data type : {full_students.dtype}')

print('processed data:', '\n',full_students)

shape of the Data: (20, 3)
size of data : 60
Data type : int32
processed data: 
 [[20 12 17]
 [16 18 20]
 [13 10 17]
 [16 16 17]
 [20 14 14]
 [17 15 17]
 [14 11 15]
 [17 11 19]
 [17 14 16]
 [14 10 16]
 [12 11 12]
 [13 14 19]
 [19 19 19]
 [18 19 12]
 [10 15 14]
 [20 14 10]
 [12 14 20]
 [13 18 16]
 [19 15 18]
 [17 12 12]]


## Data Analyse

In [43]:
data
# (4,5,3)      har 5 dar 3 yek school hesab mishe

array([[[20, 12, 17],
        [16, 18, 20],
        [13, 10, 17],
        [16, 16, 17],
        [20, 14, 14]],

       [[17, 15, 17],
        [14, 11, 15],
        [17, 11, 19],
        [17, 14, 16],
        [14, 10, 16]],

       [[12, 11, 12],
        [13, 14, 19],
        [19, 19, 19],
        [18, 19, 12],
        [10, 15, 14]],

       [[20, 14, 10],
        [12, 14, 20],
        [13, 18, 16],
        [19, 15, 18],
        [17, 12, 12]]], dtype=int32)

In [44]:
print('---- Dara Analyse Report -----\n')
# average score for each student

student_avg = np.mean(full_students, axis=1)
print(f'verage score for each student: \n{student_avg}\n')

print('----------------------------------\n')

# High amd Low Performance Students

high_end = np.percentile(full_students,70)
low_end = np.percentile(full_students,30)

high_performers = np.where(student_avg >= high_end)
low_performers = np.where(student_avg <= low_end)

print(f'High Performance Students: {high_performers}, grades: {student_avg[high_performers]}')
print(f'Low Performance Students: {low_performers}, grades: {student_avg[low_performers]}')

print('--------------------------------\n')

# find avg score for each schoole
schoole_avg = np.mean(data, axis=(1,2))
print(f'Average score among schooles: \n{schoole_avg}\n')
print(f'Schooles Ranking by avg_score:\n {sorted(list(schoole_avg))}')


---- Dara Analyse Report -----

verage score for each student: 
[16.33333333 18.         13.33333333 16.33333333 16.         16.33333333
 13.33333333 15.66666667 15.66666667 13.33333333 11.66666667 15.33333333
 19.         16.33333333 13.         14.66666667 15.33333333 15.66666667
 17.33333333 13.66666667]

----------------------------------

High Performance Students: (array([ 1, 12, 18]),), grades: [18.         19.         17.33333333]
Low Performance Students: (array([ 2,  6,  9, 10, 14, 19]),), grades: [13.33333333 13.33333333 13.33333333 11.66666667 13.         13.66666667]
--------------------------------

Average score among schooles: 
[16.         14.86666667 15.06666667 15.33333333]

Schooles Ranking by avg_score:
 [np.float64(14.866666666666667), np.float64(15.066666666666666), np.float64(15.333333333333334), np.float64(16.0)]
