## Import Libraries

In [2]:
import numpy as np

## Smart Filters

In [6]:
numbers = np.random.randint(0,13,(3,4))
numbers

array([[6, 5, 5, 6],
       [8, 0, 5, 3],
       [8, 8, 0, 6]], dtype=int32)

In [7]:
print(numbers > 5)

[[ True False False  True]
 [ True False False False]
 [ True  True False  True]]


In [ ]:
numbers[numbers > 5]   # masking

array([6, 6, 8, 8, 8, 6], dtype=int32)

In [10]:
numbers[(numbers > 5) & (numbers < 8)]

array([6, 6, 6], dtype=int32)

In [15]:
condition = (numbers > 7) | (numbers < 3)
numbers[condition]

array([8, 0, 8, 8, 0], dtype=int32)

In [34]:
b = np.arange(0,100).reshape(4,25)
b


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
p25 = np.percentile(b , 25)   #data e part
p75 = np.percentile(b , 75)

# ----- 25 ----- 75 -----

condition = (b >= p25) & (b <= p75)
c = b[condition]
print(c)
print (np.max(c))
print(np.min (c))

[25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74]
74
25
