## Import Libraries

In [2]:
import numpy as np

## Broadcasting

In [3]:
a = np.array([1,2,3,4])
b = 2
print(a*b)

[2 4 6 8]


In [5]:
a = np.array(([1,2,3,4],[5,6,7,8]))
b = np.array([1,2,3,4])
print(a*b)
print(a.shape)
print(b.shape)

[[ 1  4  9 16]
 [ 5 12 21 32]]
(2, 4)
(4,)


[
[1,2,3,4],
[5,6,7,8]
]

[
[1,2,3,4],
[1,2,3,4]
]


(2,4)
(1,4)

(2,4)


(4,1,5)
(4,3,1)

(4,3,5)