## Import Libraries

In [1]:
import numpy as np

## Indexing and Slicing

In [3]:
a = np.random.randint(0,12,(3,4))
a

array([[ 5,  5,  1,  0],
       [10,  1,  8, 10],
       [ 3,  4,  1,  5]], dtype=int32)

In [5]:
a[0:2,1:3]

array([[5, 1],
       [1, 8]], dtype=int32)

In [7]:
a[ : ,[0,3]]      #ستونای وسطو نمیهوایم و سطون اخر و اول رو به دست میاریم

array([[ 5,  0],
       [10, 10],
       [ 3,  5]], dtype=int32)

In [10]:
a[[0,2], :]      #همون بالایی ولی اینبار برای ردیف ها

array([[5, 5, 1, 0],
       [3, 4, 1, 5]], dtype=int32)

In [12]:
b = np.random.randint(0,100,(4,5))
b

array([[ 8, 10, 57, 94, 97],
       [99,  9, 65, 99, 25],
       [98, 71, 58, 45, 19],
       [49, 88, 38, 25, 64]], dtype=int32)

In [24]:
rows = np.array([0,2,3])
columns = np.array([1,3,4])
print(b[rows, columns])

rows1 = [0,2,3]
columns1 = [1,3,4]
print(b[rows1,columns1])

[10 45 64]
[10 45 64]
