
Project Title: Data Rescue Mission on the Space Station

Learning Objectives:

- Create, Reshape, Slice

- Broadcasting

- Masking and Comparison

- Advanced Indexing

- Sorting

**Story Scenario:**

In the year 2085, the International Space Station is facing a malfunction in its astronaut health monitoring system. Vital data such as heart rate, blood pressure, oxygen level, and body temperature have been stored in a disorganized manner. As a NASA medical data specialist, your mission is to clean, analyze, and prioritize this data to ensure the astronauts' health.

## Import Libraries

In [2]:
import numpy as np

1. Create and Reshape Data

In [3]:
data = np.random.randint(60,100,40)
data

array([73, 64, 70, 72, 95, 79, 93, 81, 71, 68, 87, 90, 64, 88, 77, 69, 79,
       65, 60, 62, 93, 76, 88, 61, 87, 89, 86, 80, 75, 92, 60, 88, 71, 60,
       98, 82, 60, 94, 90, 88], dtype=int32)

In [8]:
data = data.reshape(10,4)
print(f'Raw Data:\n\n{data}\n')

Raw Data:

[[73 64 70 72]
 [95 79 93 81]
 [71 68 87 90]
 [64 88 77 69]
 [79 65 60 62]
 [93 76 88 61]
 [87 89 86 80]
 [75 92 60 88]
 [71 60 98 82]
 [60 94 90 88]]



2. Normalizing and Broadcasting

In [16]:
var_mean = np.mean(data, axis=0)
print(f'Mean value for each health variable: {var_mean}')
data_normal = data - var_mean
print('\n Normalized Data:')
print(data_normal)

Mean value for each health variable: [76.8 77.5 80.9 77.3]

 Normalized Data:
[[ -3.8 -13.5 -10.9  -5.3]
 [ 18.2   1.5  12.1   3.7]
 [ -5.8  -9.5   6.1  12.7]
 [-12.8  10.5  -3.9  -8.3]
 [  2.2 -12.5 -20.9 -15.3]
 [ 16.2  -1.5   7.1 -16.3]
 [ 10.2  11.5   5.1   2.7]
 [ -1.8  14.5 -20.9  10.7]
 [ -5.8 -17.5  17.1   4.7]
 [-16.8  16.5   9.1  10.7]]


3. Smart Filter to Detect Danger

In [23]:
critical_values = np.array([40,60,80,55])

mask = (data < critical_values)
print(f'people with critical Health values: {data[mask]}')

people with critical Health values: [70 77 60 60]


4. Create a Report

In [58]:
avg_health = np.mean(data, axis=1)
print(f'mean health factors for each astronaut: \n {np.mean(data, axis=1).reshape(-1,1)}')

rankings = np.sort(avg_health)[::-1]          #az akhar be avval. az ziad be kam
print(rankings)


rankings1 = np.argsort(avg_health)[::-1] 
print(rankings1)

print('\n ranking of astronauts based on health state')
print(data[rankings1])

mean health factors for each astronaut: 
 [[69.75]
 [87.  ]
 [79.  ]
 [74.5 ]
 [66.5 ]
 [79.5 ]
 [85.5 ]
 [78.75]
 [77.75]
 [83.  ]]
[87.   85.5  83.   79.5  79.   78.75 77.75 74.5  69.75 66.5 ]
[1 6 9 5 2 7 8 3 0 4]

 ranking of astronauts based on health state
[[95 79 93 81]
 [87 89 86 80]
 [60 94 90 88]
 [93 76 88 61]
 [71 68 87 90]
 [75 92 60 88]
 [71 60 98 82]
 [64 88 77 69]
 [73 64 70 72]
 [79 65 60 62]]


## Sorting in numpy

In [33]:
a = np.random.randint(1,20,12)
a

array([19,  6,  5, 19,  3,  2, 17, 19, 18,  3,  5,  6], dtype=int32)

In [34]:
print(np.sort(a))

[ 2  3  3  5  5  6  6 17 18 19 19 19]


In [36]:
print(np.argsort(a))

[ 5  4  9  2 10 11  1  6  8  7  0  3]


In [39]:
a = np.random.randint(1,20,12).reshape(3,4)
a

array([[ 2, 10,  7,  5],
       [ 7, 11,  4,  3],
       [ 5, 10, 15,  9]], dtype=int32)

In [40]:
print(np.sort(a,axis=0))

[[ 2 10  4  3]
 [ 5 10  7  5]
 [ 7 11 15  9]]


In [41]:
print(np.sort(a,axis=1))

[[ 2  5  7 10]
 [ 3  4  7 11]
 [ 5  9 10 15]]


In [42]:
print(np.sort(a))  # be soorat pishfars axis ro 0 dar nazar migire

[[ 2  5  7 10]
 [ 3  4  7 11]
 [ 5  9 10 15]]
